export const milestoneYearsLaptop = [
  {
    id: 1,
    top: "57%",
    left: "67%",
    width: "1.5%",
    height: "20%",
    text: "2020",
  },
  {
    id: 2,
    top: "31%",
    left: "50%",
    width: "10%",
    height: "10%",
    text: "2021",
  },
  {
    id: 3,
    top: "59%",
    left: "30%",
    width: "10%",
    height: "10%",
    text: "2023",
  },
  {
    id: 4,
    top: "45.8%",
    left: "88.9%",
    width: "10%",
    height: "10%",
    text: "2016",
  },
  {
    id: 4,
    top: "31.9%",
    left: "15.5%",
    width: "10%",
    height: "10%",
    text: "Present",
  },
];

export const milestoneYearsMobile = [
  {
    id: 1,
    top: "62%",
    left: "67%",
    width: "1.5%",
    height: "20%",
    text: "2020",
  },
  {
    id: 2,
    top: "63.5%",
    left: "18%",
    width: "10%",
    height: "10%",
    text: "2021",
  },
  {
    id: 3,
    top: "33%",
    left: "65%",
    width: "10%",
    height: "10%",
    text: "2023",
  },
  {
    id: 4,
    top: "89.2%",
    left: "40.5%",
    width: "10%",
    height: "10%",
    text: "2016",
  },
  {
    id: 4,
    top: "30%",
    left: "17%",
    width: "10%",
    height: "10%",
    text: "Present",
  },
];

export const ExperienceTitleLaptop = [
  {
    id: 1,
    top: "70%",
    left: "10%",
    width: "40%",
    height: "20%",
    title: "Arizona State University",
    subtitle1: "Master of Science in Computer Science",
    subtitle2: "",
  },
  {
    id: 2,
    top: "70%",
    left: "60%",
    width: "30%",
    height: "10%",
    title: "VIT University",
    subtitle1: "Bachelor of Technology in Computer Science and Engineering",
    subtitle2: "",
  },
  {
    id: 3,
    top: "20%",
    left: "16%",
    width: "20%",
    height: "10%",
    title: "Nagarro Inc",
    subtitle1: "Software Developer",
    subtitle2: "",
  },
  {
    id: 4,
    top: "20%",
    left: "50%",
    width: "30%",
    height: "10%",
    title: "FiftyFive Technologies Pvt. Ltd.",
    subtitle1: "Software Developer",
    subtitle2: "",
  },
];

export const ExperienceTitleMobile = [
  {
    id: 1,
    top: "40%",
    left: "55%",
    width: "40%",
    height: "20%",
    title: "Arizona State University",
    subtitle1: "Master of Science in Computer Science",
    subtitle2: "",
  },
  {
    id: 2,
    top: "72%",
    left: "55%",
    width: "40%",
    height: "10%",
    title: "VIT University",
    subtitle1: "Bachelor of Technology in Computer Science",
    subtitle2: "",
  },
  {
    id: 3,
    top: "15%",
    left: "6%",
    width: "30%",
    height: "10%",
    title: "Nagarro Inc",
    subtitle1: "Software Developer",
    subtitle2: "",
  },
  {
    id: 4,
    top: "72%",
    left: "-2%",
    width: "50%",
    height: "10%",
    title: "FiftyFive Technologies",
    subtitle1: "Software Developer",
    subtitle2: "",
  },
];

export const infoButtonsLaptop = [
  {
    id: 1,
    top: "36.4%",
    left: "27.15%",
    width: "2%",
    height: "2%",
    text: "i",
  },
  {
    id: 2,
    top: "62.68%",
    left: "27.01%",
    width: "1.1rem",
    height: "1.1rem",
    text: "i",
  },
  {
    id: 3,
    top: "60.67%",
    left: "85.22%",
    width: "2%",
    height: "2%",
    text: "i",
  },
  {
    id: 4,
    top: "34.49%",
    left: "64.6%",
    width: "1.1rem",
    height: "1.1rem",
    text: "i",
  },
];

export const infoButtonsMobile = [
  {
    id: 1,
    top: "28.031%",
    left: "14.32%",
    width: "4rem",
    height: "4rem",
    text: "i",
  },
  {
    id: 2,
    top: "30.2%",
    left: "73.98%",
    width: "10%",
    height: "10%",
    text: "i",
  },
  {
    id: 3,
    top: "65.2%",
    left: "73.3%",

    width: "10%",
    height: "10%",
    text: "i",
  },
  {
    id: 4,
    top: "66.44%",
    left: "15.26%",
    width: "10%",
    height: "10%",
    text: "i",
  },
];
